---
title: "overhead"
output: html_document
date: "2023-02-20"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# this code will use the stats::kmeans() algorithm to identify clusters appearing in 
# weekly crab spider counts.

```


```{r bytheway}

# what is the rank of insect occurrence?
  
  skimr::skim(bugs.tibl)


```


```{r bug-percentages, echo=FALSE, include=TRUE, results='asis', message=F, warning=F}

library(ggplot2)
#library(gridExtra)
library(dplyr)

setwd("/Users/rcphelps/code/groq")
source('/Users/rcphelps/code/groq/bug-library.R') # for spiderArea()
source('/Users/rcphelps/code/groq/overhead.R') # for spiderArea()

if (TRUE) {
  source.url <- c("https://raw.githubusercontent.com/cordphelps/ampelos/master/data/bugs.csv")
  bugs_all.df <- read.csv(source.url, header=TRUE, row.names=NULL)
  bugs.tibl <- bugs_all.df
}



# get a list of dataframes for the individual bug types
returnList <- scanBugPercentages(bugs_all.df)

returnList <- createFamilyPercentages(returnList)


gg <- plotBugPercentages(returnList, spidersOnly=FALSE)

print(gg)

gg <- plotBugPercentages(returnList, spidersOnly=TRUE)

print(gg)

```



```{r overhead, echo=FALSE, include=T, results='asis', message=F, warning=F}

# from ampelos-overhead.Rmd
# source('/Users/rcphelps/code/groq/bug-library.R') # for spiderArea()

weeks.vector <- getWeeks(bugs_all.df)

for (i in 1:length(weeks.vector)) {
  
  reducedData.df <- selectDataAcrossTransects(data=bugs_all.df, week=quo(weeks.vector[[i]]), species=quo(Thomisidae..crab.spider.))
  
  # # A tibble: 60 × 3
  ## Groups:   positionX [10]
  #   positionX   row totalSpiders
  #       <int> <int>        <int>
  # 1         4    48            1
  # 2         4    50            0
   #3         4    52            0
   #4         4    79            0
  # 5         4    81            2
  # 6         4    83            0
  # 7        16    48            3
  # 8        16    50            0
  # 9        16    52            2
  #10        16    79            3
  ## ℹ 50 more rows
  ## ℹ Use `print(n = ...)` to see more rows

  g24 <- plotBDV9(data=reducedData.df, cap=paste("week: ", weeks.vector[[i]], sep=""))
  
  # save .png for weeks 25 and 30 as examples for the arXiv
  
  if (i == 3) {
    week = "25"
    print(g24)
    file <- paste("f.spatial.", week, ".png", sep="")
    setwd("/Users/rcphelps/code/groq/")
    saveGGpng(filename=file, subdir="png.output", gg=g24)
  }
  
   if (i == 8) {
      week = "30"
      print(g24)
      file <- paste("f.spatial.", week, ".png", sep="")
      setwd("/Users/rcphelps/code/groq/")
      saveGGpng(filename=file, subdir="png.output", gg=g24)
   }
  
}


```


```{r}


  color_list <- list("royalblue4", "royalblue3", "royalblue2", "darkorange4", "darkorange3", "darkorange2")
  

plotBDV9 <- function (data, cap) {

  gg.pair <- ggplot(data, aes(positionX, row, size=totalSpiders)) +
    
    geom_point(shape=21, colour = "black", fill = "plum", alpha=0.8) +          
    
    scale_size(range = c(1, 10)) +
    #scale_fill_continuous(low = "plum1", high = "purple4") +
    
    #scale_y_reverse(breaks = seq(40, 100, 5)) +
    scale_y_continuous(breaks=seq(40, 100, 5)) +
                      
                    #sec.axis = sec_axis(~. * 2.4384 - 103.622,         #### 8*.3048=2.4384  40*8*.3084=103.622
                     #                      breaks= seq(0, 350, 50),
                     #                      name= "distance (m)")    ) +
    
    #expand_limits(y=c(30,100)) + 
      
    scale_x_continuous(position='bottom', breaks=seq(-12,230,16)) +
                       
                       #sec.axis = sec_axis(~.*.3048,
                        #                   breaks= seq(0, 80, 10),
                        #                   name= "trap distance from field margin (m)"))  +
 
    labs( x = "trap distance from field margin (ft)", y = "vineyard row ID (10' spacing)", caption = cap) +

    annotate("rect", xmin=4, xmax=210, ymin=44,ymax=54, alpha=0.5, fill="darkorange3") +
    annotate("rect", xmin=-12, xmax=5, ymin=44 ,ymax=54, alpha=0.2, fill="red") +

    annotate("rect", xmin=4, xmax=210, ymin=79,ymax=89, alpha=0.5, fill="royalblue4") +
    annotate("rect", xmin=-12, xmax=5, ymin=79,ymax=89, alpha=0.2, fill="red") +

    annotate("text", x = 220, y = 84, label = "SNH ", colour="black") +
    annotate("text", x = 220, y = 49, label = "control", colour="black") + # fill="white", 
    
    theme_bw() +
    
    theme(legend.position="none") +
    
    coord_flip()
  
  return(gg.pair)
}

```


```{r}

squashFlip <- function(df, weekList, columnList) {
# from bug-library.R
  
  # convert row wise percent occurrance of bugs across weeks to 
  # an average of these associated insects by week

  # 
  # inbound dataframe
  #
  #        bugNames   week1Pct   week2Pct  week3Pct  ...... 
  # bugA
  # bugB   
  #
  # weeklist   : a vector of week numbers occurring in the df
  # columnList : a vector of row names ultimately to be applied as column names


  if (FALSE) {
    df <- dfShort
    weekList <- list[[3]]
    columnList <- c('otherPct', 'spiderPct', 'week')
  }

  df <- df %>% dplyr::select(-bugNames)  # remove the bugNames column
  df <- df %>% rbind(as.character(weekList)) # add a row of week numbers
  colnames(df) <- NULL
  df <- as.data.frame(t(df)) # flip  = transpose https://stackoverflow.com/questions/6778908/transpose-a-data-frame
  colnames(df) <- columnList
  options(digits=4)  # https://stackoverflow.com/questions/26734913/r-converting-from-string-to-double
  for (i in 1:length(columnList)) {
    df[,columnList[[i]]] <- as.numeric(as.character((df[,columnList[[i]]]))) # https://stackoverflow.com/questions/3796266/change-the-class-from-factor-to-numeric-of-many-columns-in-a-data-frame
  }

  # now, just create an average of insects for this particular family dataframe. columnList represents the
  # column names including 'week'. We could truncate the list to remove 'week', 
  #          like so : columnList <- columnList [ - length(columnList) ] # ignore the week column (the last column in the list)
  # and then use the modified columnList to define the columns that need to be used for the average
  #           somewhat like : df <- df %>% rowwise() %>% dplyr::mutate(meanPct=mean(columnList))
  # but mutate() is choking on that list, I think it is due to the old bogey of dyplr not accepting clean variables.
  #            the solution may be here : https://datascience.blog.wzb.eu/2016/09/27/dynamic-columnvariable-names-with-dplyr-using-standard-evaluation-functions/
  # the other approach is to remove the 'week' column, creat the average, then re-add the week column.
  #
  
  temp.df <- df
  temp.df <- temp.df %>% dplyr::select(week)                # that's a dataframe containing only week
  df <- df %>% dplyr::select(-week)                         # that's a dataframe every column except week
  df <- transform(df, sumPct = rowSums(df, na.rm = TRUE))  # finally, escaping the nightmare of dplyr https://stackoverflow.com/questions/12486264/average-across-columns-in-r-excluding-nas
  df <- dplyr::bind_cols(df, temp.df)

  # returning dataframe
  #                                     /----------- use this average for graphing purposes
  # species1.Pct .... speciesX.Pct   avePct   week
  #
  #

  return(df)

}


selectDataAcrossTransects <- function(data, week, species) {
# from bug-library.R
        #dplyr::filter(transect == UQ(t), week == UQ(w)) # last comment
        # https://www.reddit.com/r/rstats/comments/6zu5od/when_writing_functions_involving_dplyr_how_do_you/

    test.df <- data %>% 
        dplyr::filter(week == UQ(week))  %>%
        dplyr::select(positionX, row, UQ(species)) %>%
        dplyr::group_by(positionX, row) %>%
        summarize(totalSpiders = sum(UQ(species), na.rm = T))

  return(test.df)

}


```

```{r, cumulative, echo=FALSE, include=TRUE, results='asis', message=F, warning=F}

  library(ggplot2)
  library(dplyr)

  source('/Users/rcphelps/code/groq/bug-library.R')

  color_list <- list("royalblue4", "royalblue3", "royalblue2", "darkorange4", "darkorange3", "darkorange2")

if (TRUE) {
  source.url <- c("https://raw.githubusercontent.com/cordphelps/ampelos/master/data/bugs.csv")
  bugs_all.df <- read.csv(source.url, header=TRUE, row.names=NULL)
  bugs.tibl <- bugs_all.df
}

  positions.group <- list()
  positions.group[[1]] <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
  
  transects <- list()
  transects[[1]] <- "oakMargin"
  transects[[2]] <- "control"

  
  output.tibl <- tibble(crabSpiders = numeric(), 
                        transect = character(), 
                        posGroup = character(), 
                        weeksGroup = character(),
                        stateTPW = character(),
                        historical = character(),
                        percentEdge = numeric() )
  
  ####################################################################
  
  week.tibl <- bugs.tibl %>%
        dplyr::filter(time=='pm') %>%
        dplyr::select(-date, -time, -julian) %>%
        dplyr::rename(crabSpiders = Thomisidae..crab.spider.) %>%
        dplyr::mutate(transect = str_replace(transect, "oakMargin", "SNH")) %>%
        dplyr::group_by(transect, week) %>%
        dplyr::summarize(crabSpiders=sum(crabSpiders), .groups='drop'  )
  
  # get a list of the week labels ('weekXX')
  weeks <- getWeeks(week.tibl)
  # get a list of week IDs ('integers')
  weekID.list <- dissectWeeks(w=weeks)
  
  captionText <- paste("crab spiders by week", 
                       "\ndaytime: ", "pm", sep="")
  
  week.control.tibl <- week.tibl %>% dplyr::filter(transect=='control')
  week.snh.tibl <- week.tibl %>% dplyr::filter(transect=='SNH')
  
  transect = c("control" = "darkorange3", "SNH" = "royalblue3")
  
  ggWeek <- ggplot() + 

      #geom_bar(data=week.tibl, aes(y=crabSpiders, x = factor(week), fill = transect, colour = transect),
    #           stat="identity", alpha=.3, position = "dodge") +
    
          geom_bar(data=week.control.tibl, x = factor(week), aes(y=crabSpiders, fill = transect, colour = transect),
                   position = position_dodge(width = 0.7)) +
    
          geom_bar(data=week.snh.tibl, x = factor(week), aes(y=crabSpiders, fill = transect, colour = transect),
                   position = position_dodge(width = 0.7)) +
	
      scale_y_continuous(breaks = seq(min(0), max(100), by = 10)) +
	  
	     scale_x_discrete(breaks=weeks, labels=weekID.list) +

        labs(x="week number", y="crab spiders", caption = captionText ) +
    
  	theme_bw() +
	  
    theme(
          # axis.text.x = element_text(angle = 45),
          panel.border = element_rect(colour = "black", fill=NA),
          legend.position="bottom",
          legend.title = element_blank()
          ) 
  
  print(ggWeek)
  
  ####################################################################
   
  julian.tibl <- bugs.tibl %>%
        dplyr::filter(time=="pm") %>%
        dplyr::select(-date, -time) %>%
        dplyr::rename(crabSpiders = Thomisidae..crab.spider.) %>%
        dplyr::mutate(transect = str_replace(transect, "oakMargin", "SNH")) %>%
        dplyr::group_by(transect, julian) %>%
        dplyr::summarize(crabSpiders=sum(crabSpiders), .groups='drop'  ) %>%
        dplyr::group_by(transect) %>%
        dplyr::mutate(cum_spiders = cumsum(crabSpiders))
 

  captionText <- paste("crab spiders by julian day", 
                       "\ndaytime : ", "XXXXXXX", sep="")
  
  ggJulian <- ggplot() + 

      # geom_bar(data=julian.tibl, aes(y=crabSpiders, x = factor(julian), fill = transect, colour = transect), stat="identity", alpha=.3, position = "dodge") +
     
      geom_line(data=julian.tibl, aes(y=crabSpiders, x = factor(julian), colour = transect, group=transect)) +
	
      scale_y_continuous(breaks = seq(min(0), max(100), by = 10)) +

      labs(x="julian day 2018", y="crab spiders", caption = captionText ) +
    
  	  theme_bw() +
	  
      theme(
          axis.text.x = element_text(angle = 45),
          panel.border = element_rect(colour = "black", fill=NA),
          legend.position="bottom",
          legend.title = element_blank()
          ) 
  
  print(ggJulian)
  ####################################################################

  captionText <- paste("cumulative crab spiders", 
                       "\ndaytime : ", "XXXXXXXX", sep="")
     
  ggCumulative <- ggplot() + 

      # geom_bar(data=julian.tibl, aes(y=crabSpiders, x = factor(julian), fill = transect, colour = transect), stat="identity", alpha=.3, position = "dodge") +
     
      geom_line(data=julian.tibl, aes(y=cum_spiders, x = factor(julian), colour = transect, group=transect)) +
	
      scale_y_continuous(breaks = seq(min(0), max(250), by = 50)) +

      labs(x="julian day 2018", y="crab spiders", caption = captionText ) +
    
  	  theme_bw() +
	  
      theme(
          axis.text.x = element_text(angle = 45),
          panel.border = element_rect(colour = "black", fill=NA),
          legend.position="bottom",
          legend.title = element_blank()
          ) 
  
  print(ggCumulative)
  
    ####################################################################
   
  bothTimes.tibl <- bugs.tibl %>%
        dplyr::select(-date, -time) %>%
        dplyr::rename(crabSpiders = Thomisidae..crab.spider.) %>%
        dplyr::mutate(transect = str_replace(transect, "oakMargin", "SNH")) %>%
        dplyr::group_by(transect, julian) %>%
        dplyr::summarize(crabSpiders=sum(crabSpiders), .groups='drop'  ) %>%
        dplyr::group_by(transect) %>%
        dplyr::mutate(cum_spiders = cumsum(crabSpiders))
 

  captionText <- paste("crab spiders by julian day", 
                       "\nboth collection times ", sep="")
  
     
  ggBoth <- ggplot() + 

      # geom_bar(data=julian.tibl, aes(y=crabSpiders, x = factor(julian), fill = transect, colour = transect), stat="identity", alpha=.3, position = "dodge") +
     
      geom_line(data=julian.tibl, aes(y=cum_spiders, x = factor(julian), colour = transect, group=transect)) +
	
      scale_y_continuous(breaks = seq(min(0), max(250), by = 50)) +

      labs(x="julian day 2018", y="crab spiders", caption = captionText ) +
    
  	  theme_bw() +
	  
      theme(
          axis.text.x = element_text(angle = 45),
          panel.border = element_rect(colour = "black", fill=NA),
          legend.position="bottom",
          legend.title = element_blank()
          ) 
  
  print(ggBoth)
  
  
    ####################################################################
  
  if (TRUE) {
    
    # max flexibility mode for ggplot
      
    week.tibl <- bugs.tibl %>%
        dplyr::filter(transect=="control")  %>%
        dplyr::filter(time=="pm") %>%
        dplyr::select(-date, -time, -julian) %>%
        dplyr::rename(crabSpiders = Thomisidae..crab.spider.) %>%
        dplyr::group_by(transect, position, week) %>%
        dplyr::summarize(crabSpiders=sum(crabSpiders), .groups='drop'  )

      p1.tibl <- week.tibl %>% dplyr::filter(position==1)
      p2.tibl <- week.tibl %>% dplyr::filter(position==2)
      p3.tibl <- week.tibl %>% dplyr::filter(position==3)
      p4.tibl <- week.tibl %>% dplyr::filter(position==4)
      p5.tibl <- week.tibl %>% dplyr::filter(position==5)
      p6.tibl <- week.tibl %>% dplyr::filter(position==6)
      p7.tibl <- week.tibl %>% dplyr::filter(position==7)
      p8.tibl <- week.tibl %>% dplyr::filter(position==8)
      p9.tibl <- week.tibl %>% dplyr::filter(position==9)
      p10.tibl <- week.tibl %>% dplyr::filter(position==10)
  
      # get a list of the week labels ('weekXX')
      weeks <- getWeeks(p1.tibl)
      # get a list of week IDs ('integers')
      weekID.list <- dissectWeeks(w=weeks)
        captionText <- "stuff"
  
	gg.dork <- ggplot() + 

  	      geom_line(data=p1.tibl, aes(y = crabSpiders, x = factor(weeks), group=1), linewidth=1) +
	  
	        geom_jitter(data=p2.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
	        geom_jitter(data=p3.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
	        geom_jitter(data=p4.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
	        geom_jitter(data=p5.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
	        geom_jitter(data=p6.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
  	      geom_jitter(data=p7.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
	        geom_jitter(data=p8.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
  	      geom_jitter(data=p9.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	  
	        geom_jitter(data=p10.tibl, aes(y = crabSpiders, x = factor(weeks)), shape = 21, size=4) +
	
          expand_limits(y=c(0,20)) +
          scale_y_continuous(breaks = seq(min(0), max(20), by = 2)) +
	  
	        scale_x_discrete(breaks=weeks, labels=weekID.list) +

          #coord_fixed(ratio=1) + # control the aspect ratio

         labs(x="week number", y="crab spiders", caption = captionText ) +

  	theme_bw() +
	  
    theme(
          # axis.text.x = element_text(angle = 45),
          panel.border = element_rect(colour = "black", fill=NA),
          legend.position="bottom",
          legend.title = element_blank()
          ) 
	
	  print(gg.dork)
	  
  }
  

  
```

